---
ID: "000f52ca-6db6-4e81-8cd9-f6ce8f288c40"
Parent: "77d04f78-ab5f-4457-8518-3f4b040f6a95"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/Demo Site - For Estimations/Demo Site - For Estimations/Presentation/Headless Variants/PageContent/Default"
BranchID: "5abe3762-5a9c-4710-9730-bb302e90fd13"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E9B59BC9-57CB-43AC-8FD7-F9A676B0C46F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221201T092119Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Anonymous
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7d2302e1-6585-4164-9a7a-acfddd729cfc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Anonymous
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221201T092119Z
