---
ID: "faeccbf4-6897-4490-8464-7b094462ea51"
Parent: "5f4c471d-8aef-4a54-a134-f21f595094a7"
Template: "5f4c471d-8aef-4a54-a134-f21f595094a7"
Path: /sitecore/templates/Feature/CNX/PageBanner/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230731T125045Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\parvathi.somanahalli@concentrix.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\parvathi.somanahalli@concentrix.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a4bbf52d-625b-4107-ad77-1d9cc5767d60"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\parvathi.somanahalli@concentrix.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230731T125054Z
