---
ID: "c224b392-99d2-4db8-9689-e01859d0be3d"
Parent: "a90da1ec-e382-410f-a464-3889766c440c"
Template: "010163da-00a6-4599-a7c9-9ca4c79e562d"
Path: /sitecore/content/CNX Websites/Base Site/Home/Products List
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{CAC675A1-41CA-4D59-9823-B557E9775C33}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{B70167F1-AD92-4533-A4C8-5968438CA5EC}"
              s:ds=""
              s:id="{7FD707EC-638B-4390-B500-31BA8AA61B8C}"
              s:par="GridParameters&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230822T132916Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products List
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kundankumar.puri@concentrix.com
    - ID: "595f52d5-223b-4143-afa6-73415b86f877"
      Hint: Title
      Value: Products List
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kundankumar.puri@concentrix.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0cdec0fa-409b-4ab6-b0cc-8c2466cc4d1a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kundankumar.puri@concentrix.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230825T042138Z
