---
ID: "25d96353-d3c6-42df-a935-70d8241ac8b5"
Parent: "9301c680-78f3-4fa5-ac17-f314accb6104"
Template: "9301c680-78f3-4fa5-ac17-f314accb6104"
Path: /sitecore/templates/Feature/CNX/Rendering Parameters/PageBanner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e3da1d1f-6428-4bb5-924e-00362c392649"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\parvathi.somanahalli@concentrix.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230724T104401Z
